### ISSUE TITLE
repository linked from crates.io seems to be not the repo from which it was published

### ISSUE THREAD

**Issue by jqnatividad** [kindly/csvs_convert#4]
Hi @kindly,
I noticed that this repo seems to be not the repo used to publish to crates.io.

On crates.io, you have 0.7.11 last updated 18 hours ago, but the Cargo.toml here is 0.7.8 last updated 2 weeks ago.

Is there another repo? If so, why is it not the one referred to in the Cargo.toml?

**Comment by kindly** [comment]
@jqnatividad oops that is my fault, this is the correct repo.  `main` is now up to date.  Also I have added a https://github.com/kindly/csvs_convert/blob/main/changelog.md so that it is easier for you to see what has been changed and updated in each version.

Some of the bugs on `qsv` have been fixed with the later realeases.  I am currently working on dumping the `sql` without a connection.  I was going to update `qsv` once this was done.

**Comment by jqnatividad** [comment]
Thanks!
